name: "Terijaki"
short_name: "Terijaki"
title: "Terijaki"
description: "IndiDev"
logo: '/img/avatar.png'
favicon: '/icon/16.png'
apple_touch_icon: '/img/avatar.png'
apple_touch_startup_image: '/img/avatar.png'
language: 'en'
language_direction: 'ltr'
theme_color: "#0B132B"
background_color: "#0B132B"
permalink: /:title/
url: https://terijaki.com
author: "Björn Kohnen"

plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

exclude:
  - ".github/*"
  - ".gitignore"
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
  - manifest.json

collections:
  products:
    sort_by: lesson
  socials:
