name: "Terijaki"
short_name: "Terijaki"
title: "Terijaki"
description: "IndiDev"
logo: '/img/logo.png'
favicon: '/img/favicon.png'
apple_touch_icon: '/img/apple-touch-icon.png'
apple_touch_startup_image: '/img/apple-touch-icon.png'
language: 'en'
language_direction: 'ltr'
theme_color: "#1C2541"
background_color: "#0B132B"
permalink: /:title/
url: https://terijaki.com
author: "Björn Kohnen"

plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

exclude:
  - ".github/workflows*"
  - ".gitignore"
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
